import { PixelConfig } from './PixelConfig';

export interface DownloadGateProps {
  id: string;
  userId: number;
  slug: string;
  title: string;
  artistName: string | null;
  genre: string | null;
  description: string | null;
  artworkUrl: string | null;
  soundcloudTrackId: string | null;
  soundcloudTrackUrl: string | null;
  soundcloudUserId: string | null;
  fileUrl: string;
  fileSizeMb: number | null;
  fileType: string | null;
  requireEmail: boolean;
  requireSoundcloudRepost: boolean;
  requireSoundcloudFollow: boolean;
  requireSpotifyConnect: boolean;
  requireInstagramFollow: boolean;
  instagramProfileUrl: string | null;
  active: boolean;
  maxDownloads: number | null;
  expiresAt: Date | null;
  pixelConfig: PixelConfig | null;
  createdAt: Date;
  updatedAt: Date;
}

export class DownloadGate {
  private constructor(private readonly props: DownloadGateProps) {
    this.validate();
  }

  private validate(): void {
    if (!this.props.slug || this.props.slug.trim().length === 0) {
      throw new Error('Slug is required');
    }
    if (!this.props.title || this.props.title.trim().length === 0) {
      throw new Error('Title is required');
    }
    if (!this.props.fileUrl || this.props.fileUrl.trim().length === 0) {
      throw new Error('File URL is required');
    }
  }

  get id(): string { return this.props.id; }
  get userId(): number { return this.props.userId; }
  get slug(): string { return this.props.slug; }
  get title(): string { return this.props.title; }
  get artistName(): string | null { return this.props.artistName; }
  get genre(): string | null { return this.props.genre; }
  get description(): string | null { return this.props.description; }
  get artworkUrl(): string | null { return this.props.artworkUrl; }
  get soundcloudTrackId(): string | null { return this.props.soundcloudTrackId; }
  get soundcloudTrackUrl(): string | null { return this.props.soundcloudTrackUrl; }
  get soundcloudUserId(): string | null { return this.props.soundcloudUserId; }
  get fileUrl(): string { return this.props.fileUrl; }
  get fileSizeMb(): number | null { return this.props.fileSizeMb; }
  get fileType(): string | null { return this.props.fileType; }
  get requireEmail(): boolean { return this.props.requireEmail; }
  get requireSoundcloudRepost(): boolean { return this.props.requireSoundcloudRepost; }
  get requireSoundcloudFollow(): boolean { return this.props.requireSoundcloudFollow; }
  get requireSpotifyConnect(): boolean { return this.props.requireSpotifyConnect; }
  get requireInstagramFollow(): boolean { return this.props.requireInstagramFollow; }
  get instagramProfileUrl(): string | null { return this.props.instagramProfileUrl; }
  get active(): boolean { return this.props.active; }
  get maxDownloads(): number | null { return this.props.maxDownloads; }
  get expiresAt(): Date | null { return this.props.expiresAt; }
  get pixelConfig(): PixelConfig | null { return this.props.pixelConfig; }
  get createdAt(): Date { return this.props.createdAt; }
  get updatedAt(): Date { return this.props.updatedAt; }

  isActive(): boolean {
    if (!this.props.active) return false;
    if (this.props.expiresAt && this.props.expiresAt < new Date()) return false;
    return true;
  }

  static fromDatabase(props: DownloadGateProps): DownloadGate {
    return new DownloadGate(props);
  }

  static create(props: Omit<DownloadGateProps, 'id' | 'createdAt' | 'updatedAt' | 'active'>): DownloadGate {
    const now = new Date();
    return new DownloadGate({
      ...props,
      id: '', // To be generated by DB
      active: true,
      createdAt: now,
      updatedAt: now
    });
  }
}
