
export interface DownloadSubmissionProps {
  id: string;
  gateId: string;
  email: string;
  firstName?: string | null;
  soundcloudUserId?: string | null;
  soundcloudUsername?: string | null;
  soundcloudPermalink?: string | null;
  spotifyUserId?: string | null;
  spotifyDisplayName?: string | null;
  emailVerified: boolean;
  soundcloudRepostVerified: boolean;
  soundcloudRepostVerifiedAt?: Date | null;
  soundcloudFollowVerified: boolean;
  soundcloudFollowVerifiedAt?: Date | null;
  spotifyConnected: boolean;
  spotifyConnectedAt?: Date | null;
  downloadToken?: string | null;
  downloadTokenGeneratedAt?: Date | null;
  downloadTokenExpiresAt?: Date | null;
  downloadCompleted: boolean;
  downloadCompletedAt?: Date | null;
  consentMarketing: boolean;
  ipAddress?: string | null;
  userAgent?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export class DownloadSubmission {
  private constructor(private readonly props: DownloadSubmissionProps) {
    this.validate();
  }

  private validate(): void {
    if (!this.props.email || !this.props.email.includes('@')) {
      throw new Error('Valid email is required');
    }
  }

  get id(): string { return this.props.id; }
  get gateId(): string { return this.props.gateId; }
  get email(): string { return this.props.email; }
  get firstName(): string | null | undefined { return this.props.firstName; }
  get soundcloudUserId(): string | null | undefined { return this.props.soundcloudUserId; }
  get soundcloudUsername(): string | null | undefined { return this.props.soundcloudUsername; }
  get soundcloudPermalink(): string | null | undefined { return this.props.soundcloudPermalink; }
  get spotifyUserId(): string | null | undefined { return this.props.spotifyUserId; }
  get spotifyDisplayName(): string | null | undefined { return this.props.spotifyDisplayName; }
  
  get emailVerified(): boolean { return this.props.emailVerified; }
  get soundcloudRepostVerified(): boolean { return this.props.soundcloudRepostVerified; }
  get soundcloudRepostVerifiedAt(): Date | null | undefined { return this.props.soundcloudRepostVerifiedAt; }
  get soundcloudFollowVerified(): boolean { return this.props.soundcloudFollowVerified; }
  get soundcloudFollowVerifiedAt(): Date | null | undefined { return this.props.soundcloudFollowVerifiedAt; }
  get spotifyConnected(): boolean { return this.props.spotifyConnected; }
  get spotifyConnectedAt(): Date | null | undefined { return this.props.spotifyConnectedAt; }
  
  get downloadToken(): string | null | undefined { return this.props.downloadToken; }
  get downloadTokenGeneratedAt(): Date | null | undefined { return this.props.downloadTokenGeneratedAt; }
  get downloadTokenExpiresAt(): Date | null | undefined { return this.props.downloadTokenExpiresAt; }
  
  get downloadCompleted(): boolean { return this.props.downloadCompleted; }
  get downloadCompletedAt(): Date | null | undefined { return this.props.downloadCompletedAt; }
  
  get consentMarketing(): boolean { return this.props.consentMarketing; }
  get ipAddress(): string | null | undefined { return this.props.ipAddress; }
  get userAgent(): string | null | undefined { return this.props.userAgent; }
  get createdAt(): Date { return this.props.createdAt; }
  get updatedAt(): Date { return this.props.updatedAt; }

  static fromDatabase(props: DownloadSubmissionProps): DownloadSubmission {
    return new DownloadSubmission(props);
  }

  static create(props: Pick<DownloadSubmissionProps, 'gateId' | 'email' | 'firstName' | 'consentMarketing' | 'ipAddress' | 'userAgent'>): DownloadSubmission {
    const now = new Date();
    return new DownloadSubmission({
      ...props,
      id: '', // To be generated by DB
      emailVerified: false,
      soundcloudRepostVerified: false,
      soundcloudFollowVerified: false,
      spotifyConnected: false,
      downloadCompleted: false,
      createdAt: now,
      updatedAt: now
    });
  }
}
